export const en = {
  appTitle: 'AgriBOS',
  companyName: 'SRI BASAVESHWARA & CO.',
  ownerName: 'Doddana Gowda',
  welcome: 'Welcome to AgriBOS Platform',
  loginTitle: 'Sign In to AgriBOS',
  usernameOrMobile: 'Username or Mobile Number',
  password: 'Password',
  signInButton: 'Sign In to Portal',
  signingIn: 'Authenticating...',
  logout: 'Sign Out',
  dashboard: 'Dashboard',
  systemStatus: 'System Platform Status',
  activeSession: 'Active Operator Session',
  role: 'Role',
  proprietor: 'Proprietor',
  accountant: 'Accountant',
  fleetManager: 'Fleet Manager',
  fieldClerk: 'Field Clerk',
  language: 'Language',
  theme: 'Theme',
  operations: 'Operations',
  bookings: 'Field Bookings',
  dispatches: 'Machine Dispatches',
  workExecution: 'Daily Work Logs',
  todaysBookings: "Today's Bookings",
  machinesWorking: 'Machines Working',
  machinesAvailable: 'Machines Available',
  operatorsWorking: 'Active Operators',
  dispatchesToday: 'Dispatches Today',
  jobsInProgress: 'Jobs In Progress',
  completedJobs: 'Completed Jobs',
  createBooking: 'New Booking',
  bookingNumber: 'Booking #',
  farmer: 'Farmer',
  village: 'Village',
  crop: 'Crop',
  machineType: 'Machine Type',
  estimatedAcres: 'Estimated Acres',
  status: 'Status',
  priority: 'Priority',
  actions: 'Actions',
  dieselResponsibility: 'Diesel Responsibility',
  companyProvided: 'Company Provided',
  farmerProvided: 'Farmer Provided',
  shared: 'Shared',
  startHourMeter: 'Start Hour Meter',
  endHourMeter: 'End Hour Meter',
  actualAcres: 'Actual Acres',
  logWork: 'Log Work Entry',
  addBreak: 'Record Break',
  dispatchMachine: 'Dispatch Machine',
  fuelManagement: 'Fuel Management',
  fuelDashboard: 'Fuel Dashboard',
  fuelVouchers: 'Fuel Vouchers',
  fuelLogs: 'Refuel Logs',
  issueVoucher: 'Issue Fuel Voucher',
  totalLiters: 'Total Liters Refueled',
  totalFuelCost: 'Total Fuel Cost',
  activeVouchers: 'Active Vouchers',
  usedVouchers: 'Used Vouchers',
  verifiedVouchers: 'Verified Vouchers',
  fuelEfficiency: 'Avg Fuel Efficiency',
  voucherNumber: 'Voucher Number',
  maxLiters: 'Max Allowed Liters',
  expiresAt: 'Expires At',
  workshopDashboard: 'Workshop Dashboard',
  breakdowns: 'Field Breakdowns',
  maintenanceJobs: 'Maintenance Jobs',
  reportBreakdown: 'Report Breakdown',
  activeBreakdowns: 'Active Breakdowns',
  machinesUnderMaintenance: 'Under Maintenance',
  jobsWaitingParts: 'Waiting for Parts',
  serviceDue: 'Service Due Thresholds',
  breakdownNumber: 'Breakdown Number',
  jobNumber: 'Job Number',
  severity: 'Severity',
  category: 'Category',
  assignTechnician: 'Assign Technician',
  inventoryDashboard: 'Inventory Dashboard',
  spareParts: 'Spare Parts Catalog',
  purchaseOrders: 'Purchase Orders',
  suppliers: 'Suppliers & Vendors',
  addPart: 'Add Spare Part',
  createPO: 'New Purchase Order',
  currentInventoryValue: 'Current Inventory Value',
  lowStockItems: 'Low Stock Alert Items',
  pendingPOs: 'Pending Purchase Orders',
  totalSuppliers: 'Registered Suppliers',
  partNumber: 'Part Number',
  partName: 'Part Name',
  stock: 'Current Stock',
  unitCost: 'Unit Cost',
  rack: 'Rack Location',
  machineHealth: 'Machine Health Score',
  fleetAnalytics: 'Fleet Analytics & KPIs',
  healthScore: 'Health Score',
  healthStatus: 'Health Status',
  mtbf: 'MTBF (Hours)',
  mttr: 'MTTR (Hours)',
  availability: 'Fleet Availability',
  financeDashboard: 'Finance Dashboard',
  invoices: 'Customer Invoices',
  farmerLedger: 'Farmer Credit Ledger (Udhar)',
  billedRevenue: 'Total Billed Revenue',
  outstandingReceivables: 'Outstanding Receivables (Udhar)',
  collectedRevenue: 'Total Collected Revenue',
  invoiceNumber: 'Invoice Number',
  amount: 'Total Amount',
  balanceDue: 'Balance Due',
  dueDate: 'Due Date',
  receipts: 'Payment Receipts',
  cashBook: 'Cash Book Ledger',
  recordReceipt: 'Record Payment Receipt',
  receiptNumber: 'Receipt #',
  paymentMode: 'Payment Mode',
  referenceNo: 'Reference # / UTR',
  cashInHand: 'Cash In Hand',
  vendorBills: 'Vendor Bills & Payables',
  payroll: 'Payroll & Operator Commissions',
  billNumber: 'Bill Number',
  vendorInvoice: 'Supplier Invoice #',
  netPayable: 'Net Payable',
  threeWayMatch: '3-Way Matched',
  generalLedger: 'General Ledger',
  trialBalance: 'Trial Balance Report',
  profitAndLoss: 'Profit & Loss Statement',
  balanceSheet: 'Balance Sheet Statement',
  batchNumber: 'Journal Batch #',
  totalDebit: 'Total Debit',
  totalCredit: 'Total Credit',
  netProfit: 'Net Profit / (Loss)',
  totalAssets: 'Total Assets',
  totalLiabilities: 'Total Liabilities & Equity',
  // Master & Entity Data
  farmers: 'Farmers',
  farmersDirectory: 'Farmers Directory',
  addFarmer: 'Add New Farmer',
  employees: 'Employees & Operators',
  driversDirectory: 'Drivers Directory',
  machines: 'Machines & Equipment',
  vehicleCompliance: 'Vehicle Compliance',
  machineOwners: 'Machine Owners',
  rentedFleet: 'Rented Fleet Owners',
  settlementLedger: 'Settlement Ledger',
  masters: 'System Master Setup',

  // Compliance & Registration
  complianceLedger: 'Vehicle Compliance Ledger',
  insuranceNo: 'Insurance Policy #',
  insuranceExp: 'Insurance Expiry',
  taxNo: 'Road Tax Token #',
  taxExp: 'Road Tax Expiry',
  permitNo: 'NC Permit #',
  fitnessExp: 'Fitness Cert Expiry',
  valid: 'VALID',
  expiringSoon: 'EXPIRING SOON',
  expired: 'EXPIRED',
  recordRenewal: 'Record Renewal',
  whatsAppAlert: 'Send WhatsApp Alert',

  // PDF & Printable Receipts
  officialInvoice: 'OFFICIAL BILL RECEIPT',
  machineBillingLedger: 'Machine Billing Ledger',
  createMachineBill: 'New Machine Bill Entry',
  manualBillNo: 'Manual Bill #',
  breakHours: 'Break / Pauses',
  netBillableHours: 'Net Billable Hours',
  ratePerUnit: 'Rate / Unit',
  totalAmount: 'Total Amount',
  advancePaid: 'Advance Paid',
  settledPayment: 'Settled Payment',
  balanceDueUdhar: 'Balance Due (Udhar)',
  printOfficialBill: 'Print Official Bill Receipt',
  downloadPdf: 'Download PDF Invoice',
  shareWhatsApp: 'Share on WhatsApp',
  proprietorHeader: 'Proprietor: Doddana Gowda',
  authorizedSignatory: 'Authorized Signatory',
};

