export const kn = {
  appTitle: 'ಆಗ್ರಿ-ಬಾಸ್ (AgriBOS)',
  companyName: 'ಶ್ರೀ ಬಸವೇಶ್ವರ ಮತ್ತು ಕಂಪನಿ',
  ownerName: 'ದೊಡ್ಡಣ ಗೌಡ',
  welcome: 'ಆಗ್ರಿ-ಬಾಸ್‌ಗೆ ಸುಸ್ವಾಗತ',
  loginTitle: 'ಆಗ್ರಿ-ಬಾಸ್‌ಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
  usernameOrMobile: 'ಬಳಕೆದಾರರ ಹೆಸರು ಅಥವಾ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
  password: 'ಪಾಸ್‌ವರ್ಡ್',
  signInButton: 'ಲಾಗಿನ್ ಮಾಡಿ',
  signingIn: 'ದೃಢೀಕರಿಸಲಾಗುತ್ತಿದೆ...',
  logout: 'ಸೈನ್ ಔಟ್',
  dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  systemStatus: 'ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ',
  activeSession: 'ಸಕ್ರಿಯ ಬಳಕೆದಾರ',
  role: 'ಪಾತ್ರ',
  proprietor: 'ಮಾಲೀಕರು',
  accountant: 'ಲೆಕ್ಕಪರಿಶೋಧಕರು',
  fleetManager: 'ಫಿಲ್ಡ್ ಮ್ಯಾನೇಜರ್',
  fieldClerk: 'ಫೀಲ್ಡ್ ಕ್ಲರ್ಕ್',
  language: 'ಭಾಷೆ',
  theme: 'ಥೀಮ್',
  operations: 'ಕಾರ್ಯಾಚರಣೆಗಳು',
  bookings: 'ಬುಕಿಂಗ್‌ಗಳು',
  dispatches: 'ಯಂತ್ರ ರವಾನೆ',
  workExecution: 'ದೈನಂದಿನ ಕೆಲಸದ ದಾಖಲೆ',
  todaysBookings: 'ಇಂದಿನ ಬುಕಿಂಗ್‌ಗಳು',
  machinesWorking: 'ಕೆಲಸ ಮಾಡುತ್ತಿರುವ ಯಂತ್ರಗಳು',
  machinesAvailable: 'ಲಭ್ಯವಿರುವ ಯಂತ್ರಗಳು',
  operatorsWorking: 'ಸಕ್ರಿಯ ಆಪರೇಟರ್‌ಗಳು',
  dispatchesToday: 'ಇಂದಿನ ರವಾನೆಗಳು',
  jobsInProgress: 'ಪ್ರಗತಿಯಲ್ಲಿರುವ ಕೆಲಸಗಳು',
  completedJobs: 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು',
  createBooking: 'ಹೊಸ ಬುಕಿಂಗ್',
  bookingNumber: 'ಬುಕಿಂಗ್ ಸಂಖ್ಯೆ',
  farmer: 'ರೈತರು',
  village: 'ಗ್ರಾಮ',
  crop: 'ಬೆಳೆ',
  machineType: 'ಯಂತ್ರದ ಪ್ರಕಾರ',
  estimatedAcres: 'ಅಂದಾಜು ಎಕರೆ',
  status: 'ಸ್ಥಿತಿ',
  priority: 'ಆದ್ಯತೆ',
  actions: 'ಕ್ರಿಯೆಗಳು',
  dieselResponsibility: 'ಡೀಸೆಲ್ ಜವಾಬ್ದಾರಿ',
  companyProvided: 'ಕಂಪನಿ ಒದಗಿಸಿದ್ದು',
  farmerProvided: 'ರೈತರು ಒದಗಿಸಿದ್ದು',
  shared: 'ಹಂಚಿಕೊಂಡದ್ದು',
  startHourMeter: 'ಆರಂಭಿಕ ಹವರ್ ಮೀಟರ್',
  endHourMeter: 'ಅಂತಿಮ ಹವರ್ ಮೀಟರ್',
  actualAcres: 'ವಾಸ್ತವ ಎಕರೆ',
  logWork: 'ಕೆಲಸ ನಮೂದಿಸಿ',
  addBreak: 'ವಿರಾಮ ದಾಖಲಿಸಿ',
  dispatchMachine: 'ಯಂತ್ರ ರವಾನಿಸಿ',
  fuelManagement: 'ಇಂಧನ ನಿರ್ವಹಣೆ',
  fuelDashboard: 'ಇಂಧನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  fuelVouchers: 'ಇಂಧನ ವೋಚರ್‌ಗಳು',
  fuelLogs: 'ರೀಫ್ಯುಯೆಲ್ ದಾಖಲೆಗಳು',
  issueVoucher: 'ವೋಚರ್ ನೀಡಿ',
  totalLiters: 'ಒಟ್ಟು ಡೀಸೆಲ್ ಲೀಟರ್‌ಗಳು',
  totalFuelCost: 'ಒಟ್ಟು ಇಂಧನ ವೆಚ್ಚ',
  activeVouchers: 'ಸಕ್ರಿಯ ವೋಚರ್‌ಗಳು',
  usedVouchers: 'ಬಳಸಿದ ವೋಚರ್‌ಗಳು',
  verifiedVouchers: 'ಪರಿಶೀಲಿಸಿದ ವೋಚರ್‌ಗಳು',
  fuelEfficiency: 'ಸರಾಸರಿ ಇಂಧನ ದಕ್ಷತೆ',
  voucherNumber: 'ವೋಚರ್ ಸಂಖ್ಯೆ',
  maxLiters: 'ಗರಿಷ್ಠ ಲೀಟರ್‌ಗಳು',
  expiresAt: 'ಮುಕ್ತಾಯದ ದಿನಾಂಕ',
  workshopDashboard: 'ವರ್ಕ್‌ಶಾಪ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  breakdowns: 'ಕ್ಷೇತ್ರ ಬ್ರೇಕ್‌ಡೌನ್‌ಗಳು',
  maintenanceJobs: 'ನಿರ್ವಹಣೆ ಕೆಲಸಗಳು',
  reportBreakdown: 'ಬ್ರೇಕ್‌ಡೌನ್ ವರದಿ ಮಾಡಿ',
  activeBreakdowns: 'ಸಕ್ರಿಯ ಬ್ರೇಕ್‌ಡೌನ್‌ಗಳು',
  machinesUnderMaintenance: 'ರಿಪೇರಿಯಲ್ಲಿರುವ ಯಂತ್ರಗಳು',
  jobsWaitingParts: 'ಸ್ಪೇರ್‌ಗಳಿಗಾಗಿ ಕಾಯುತ್ತಿದೆ',
  serviceDue: 'ಸರ್ವಿಸ್ ಬಾಕಿ ಯಂತ್ರಗಳು',
  breakdownNumber: 'ಬ್ರೇಕ್‌ಡೌನ್ ಸಂಖ್ಯೆ',
  jobNumber: 'ಕೆಲಸದ ಸಂಖ್ಯೆ',
  severity: 'ತೀವ್ರತೆ',
  category: 'ವರ್ಗ',
  assignTechnician: 'ತಂತ್ರಜ್ಞರನ್ನು ನಿಯೋಜಿಸಿ',
  inventoryDashboard: 'ದಾಸ್ತಾನು ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  spareParts: 'ಸ್ಪೇರ್ ಪಾರ್ಟ್ಸ್ ಪಟ್ಟಿ',
  purchaseOrders: 'ಖರೀದಿ ಆದೇಶಗಳು',
  suppliers: 'ಸರಬರಾಜುದಾರರು',
  addPart: 'ಸ್ಪೇರ್ ಪಾರ್ಟ್ ಸೇರಿಸಿ',
  createPO: 'ಹೊಸ ಖರೀದಿ ಆದೇಶ',
  currentInventoryValue: 'ಒಟ್ಟು ದಾಸ್ತಾನು ಮೌಲ್ಯ',
  lowStockItems: 'ಕಡಿಮೆ ದಾಸ್ತಾನು ಐಟಂಗಳು',
  pendingPOs: 'ಬಾಕಿ ಖರೀದಿ ಆದೇಶಗಳು',
  totalSuppliers: 'ಸರಬರಾಜುದಾರರ ಸಂಖ್ಯೆ',
  partNumber: 'ಪಾರ್ಟ್ ಸಂಖ್ಯೆ',
  partName: 'ಪಾರ್ಟ್ ಹೆಸರು',
  stock: 'ಪ್ರಸ್ತುತ ದಾಸ್ತಾನು',
  unitCost: 'ಘಟಕ ವೆಚ್ಚ',
  rack: 'ರ್ಯಾಕ್ ಸ್ಥಳ',
  machineHealth: 'ಯಂತ್ರದ ಆರೋಗ್ಯ ಸ್ಕೋರ್',
  fleetAnalytics: 'ಫ್ಲೀಟ್ ಅನಾಲಿಟಿಕ್ಸ್',
  healthScore: 'ಆರೋಗ್ಯ ಸ್ಕೋರ್',
  healthStatus: 'ಆರೋಗ್ಯ ಸ್ಥಿತಿ',
  mtbf: 'MTBF (ಗಂಟೆಗಳು)',
  mttr: 'MTTR (ಗಂಟೆಗಳು)',
  availability: 'ಫ್ಲೀಟ್ ಲಭ್ಯತೆ',
  financeDashboard: 'ಆರ್ಥಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  invoices: 'ಗ್ರಾಹಕರ ಇನ್‌ವಾಯ್ಸ್‌ಗಳು',
  farmerLedger: 'ರೈತರ ಉದ್ರಿ ಲೆಡ್ಜರ್ (Udhar)',
  billedRevenue: 'ಒಟ್ಟು ಬಿಲ್ ಮಾಡಿದ ಆದಾಯ',
  outstandingReceivables: 'ಬಾಕಿ ವಸೂಲಾತಿ (Udhar)',
  collectedRevenue: 'ಒಟ್ಟು ಸಂಗ್ರಹಿಸಿದ ಆದಾಯ',
  invoiceNumber: 'ಇನ್‌ವಾಯ್ಸ್ ಸಂಖ್ಯೆ',
  amount: 'ಒಟ್ಟು ಮೊತ್ತ',
  balanceDue: 'ಬಾಕಿ ಮೊತ್ತ',
  dueDate: 'ಅಂತಿಮ ದಿನಾಂಕ',
  receipts: 'ಪಾವತಿ ರಸೀದಿಗಳು',
  cashBook: 'ಕ್ಯಾಶ್ ಬುಕ್ ಲೆಡ್ಜರ್',
  recordReceipt: 'ರಸೀದಿ ನಮೂದಿಸಿ',
  receiptNumber: 'ರಸೀದಿ ಸಂಖ್ಯೆ',
  paymentMode: 'ಪಾವತಿ ವಿಧಾನ',
  referenceNo: 'ಉಲ್ಲೇಖ ಸಂಖ್ಯೆ / UTR',
  cashInHand: 'ಕೈಯಲ್ಲಿರುವ ನಗದು',
  vendorBills: 'ಸರಬರಾಜುದಾರರ ಬಿಲ್‌ಗಳು',
  payroll: 'ವೇತನ ಮತ್ತು ಆಪರೇಟರ್ ಕಮಿಷನ್',
  billNumber: 'ಬಿಲ್ ಸಂಖ್ಯೆ',
  vendorInvoice: 'ಸರಬರಾಜುದಾರರ ಇನ್‌ವಾಯ್ಸ್ #',
  netPayable: 'ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ',
  threeWayMatch: '3-ವೇ ಮ್ಯಾಚ್',
  generalLedger: 'ಜನರಲ್ ಲೆಡ್ಜರ್',
  trialBalance: 'ಟ್ರಯಲ್ ಬ್ಯಾಲೆನ್ಸ್ ವರದಿ',
  profitAndLoss: 'ಲಾಭ ಮತ್ತು ನಷ್ಟದ ಪಟ್ಟಿ (P&L)',
  balanceSheet: 'ಬ್ಯಾಲೆನ್ಸ್ ಶೀಟ್ ವರದಿ',
  batchNumber: 'ಜರ್ನಲ್ ಬ್ಯಾಚ್ #',
  totalDebit: 'ಒಟ್ಟು ಡೆಬಿಟ್',
  totalCredit: 'ಒಟ್ಟು ಕ್ರೆಡಿಟ್',
  netProfit: 'ನಿವ್ವಳ ಲಾಭ / (ನಷ್ಟ)',
  totalAssets: 'ಒಟ್ಟು ಆಸ್ತಿಗಳು',
  totalLiabilities: 'ಒಟ್ಟು ಹೊಣೆಗಾರಿಕೆಗಳು ಮತ್ತು ಈಕ್ವಿಟಿ',
  // Master & Entity Data
  farmers: 'ರೈತರು',
  farmersDirectory: 'ರೈತರ ಪಟ್ಟಿ',
  addFarmer: 'ಹೊಸ ರೈತರನ್ನು ಸೇರಿಸಿ',
  employees: 'ಉದ್ಯೋಗಿಗಳು ಮತ್ತು ಆಪರೇಟರ್‌ಗಳು',
  driversDirectory: 'ಚಾಲಕರ/ಆಪರೇಟರ್ ಪಟ್ಟಿ',
  machines: 'ಯಂತ್ರಗಳು ಮತ್ತು ಉಪಕರಣಗಳು',
  vehicleCompliance: 'ವಾಹನ ದಾಖಲೆಗಳು (ಕಂಪ್ಲೈಯನ್ಸ್)',
  machineOwners: 'ಯಂತ್ರದ ಮಾಲೀಕರು',
  rentedFleet: 'ಬಾಡಿಗೆ ಯಂತ್ರ ಮಾಲೀಕರು',
  settlementLedger: 'ಹಣಕಾಸು ಇತ್ಯರ್ಥ ಲೆಡ್ಜರ್',
  masters: 'ಸಿಸ್ಟಮ್ ಮಾಸ್ಟರ್‌ಗಳು',

  // Compliance & Registration
  complianceLedger: 'ವಾಹನ ದಾಖಲೆಗಳ ಲೆಡ್ಜರ್',
  insuranceNo: 'ಇನ್ಶೂರೆನ್ಸ್ ಪಾಲಿಸಿ ಸಂಖ್ಯೆ',
  insuranceExp: 'ಇನ್ಶೂರೆನ್ಸ್ ಮುಕ್ತಾಯ',
  taxNo: 'ರೋಡ್ ಟ್ಯಾಕ್ಸ್ ಟೋಕನ್ #',
  taxExp: 'ರೋಡ್ ಟ್ಯಾಕ್ಸ್ ಮುಕ್ತಾಯ',
  permitNo: 'NC ಪರ್ಮಿಟ್ ಸಂಖ್ಯೆ',
  fitnessExp: 'ಫಿಟ್‌ನೆಸ್ ಸರ್ಟಿಫಿಕೇಟ್ ಮುಕ್ತಾಯ',
  valid: 'ಸರಿಯಾಗಿದೆ (VALID)',
  expiringSoon: 'ಶೀಘ್ರ ಮುಕ್ತಾಯ',
  expired: 'ಅವಧಿ ಮುಗಿದಿದೆ',
  recordRenewal: 'ದಾಖಲೆ ನವೀಕರಿಸಿ (Renewal)',
  whatsAppAlert: 'ವಾಟ್ಸಾಪ್ ಅಲರ್ಟ್ ಕಳುಹಿಸಿ',

  // PDF & Printable Receipts
  officialInvoice: 'ಅಧಿಕೃತ ಬಿಲ್ ರಸೀದಿ',
  machineBillingLedger: 'ಯಂತ್ರ ಬಿಲ್ಲಿಂಗ್ ಲೆಡ್ಜರ್',
  createMachineBill: 'ಹೊಸ ಯಂತ್ರ ಬಿಲ್ ನಮೂದು',
  manualBillNo: 'ಮ್ಯಾನುವಲ್ ಬಿಲ್ ಸಂಖ್ಯೆ',
  breakHours: 'ವಿರಾಮ ಸಮಯ',
  netBillableHours: 'ನಿವ್ವಳ ಬಿಲ್ ಸಮಯ (ಗಂಟೆಗಳು)',
  ratePerUnit: 'ದರ / ಗಂಟೆ ಅಥವಾ ಎಕರೆಗೆ',
  totalAmount: 'ಒಟ್ಟು ಬಿಲ್ ಮೊತ್ತ',
  advancePaid: 'ಮುಂಗಡ ನೀಡಿದ್ದು (Advance)',
  settledPayment: 'ಪಾವತಿಸಿದ ಮೊತ್ತ',
  balanceDueUdhar: 'ಬಾಕಿ ಉಳಿದ ಹಣ (ಉದ್ರಿ)',
  printOfficialBill: 'ಅಧಿಕೃತ ಬಿಲ್ ರಸೀದಿ ಪ್ರಿಂಟ್ ಮಾಡಿ',
  downloadPdf: 'PDF ಬಿಲ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
  shareWhatsApp: 'ವಾಟ್ಸಾಪ್‌ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
  proprietorHeader: 'ಮಾಲೀಕರು: ದೊಡ್ಡಣ ಗೌಡ',
  authorizedSignatory: 'ಅಧಿಕೃತ ಸಹಿ',
};

